### ISSUE TITLE
Clarify that one needs to obtain a license to run this project

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-assisted-prescription#367]
With the new license service it is now required to supply the licensing info, which is not obvious. Perhaps the deploy scripts (local.sh / swarm.sh) could fail requiring the values to be set.

**Comment by janmiderback** [comment]
The licensing info required is the env vars
- `LICENSES_SERIAL_NBR`
- `LICENSES_CONTROL_NBR`
(if I'm correct).

We could add a check to see if these are set in the scripts and update the examples in the repo documentation to make it clear that these need to be provided to the scripts. Sounds ok?

**Comment by peol** [comment]
@janmiderback Yes!
