### ISSUE TITLE
Kibana dashboard not initialized

### ISSUE THREAD

**Issue by stefanwalther** [qlik-oss/core-assisted-prescription#56]
### Description

I expect /kibana to start with some pre-defined dashboards, but instead I just get the screen that I have to set the index, etc.

![image](https://cloud.githubusercontent.com/assets/669728/26681671/384684a8-46de-11e7-805b-43abe8a3b3e0.png)

### Steps to Reproduce

1. Created cluster as described (and using the scripts provided)
2. `deploy-stack.sh` && wait a few mins ...
3. ...

##### Expected behavior

Kibana shows up with a pre-defined dashboard.

##### Actual behavior

See above

### Versions

* qliktive-custom-analytics: `428a1c45c75949d0a1b9c2a305b041497a8787cf`
* Browser: Chrome
* Operating system: OSX
* Docker version: Docker version 17.03.1-ce, build c6d412e
* Docker-Machine version: docker-machine version 0.10.0, build 76ed2a6

**Comment by sublibra** [comment]
No priority adding example dashboard to the use case.
